apps/detector/views.py
import random
import uuid
from pathlib import Path

import cv2
import numpy as np
import torch
import torchvision
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)
from flask_login import current_user, login_required
from PIL import Image
from sqlalchemy.exc import SQLAlchemyError

from apps.app import db
from apps.crud.models import User
from apps.detector.forms import DeleteForm, DetectorForm, UploadImageForm
from apps.detector.models import UserImage, UserImageTag

# Specify template_folter ( but not static )
dt = Blueprint("detector", __name__, template_folder="templates")


# colorize border color
def make_color(labels):
    colors = [[random.randint(0, 255) for _ in range(3)] for _ in labels]
    color = random.choice(colors)
    return color


def make_line(result_image):
    line = round(0.002 * max(result_image.shape[0:2])) + 1
    return line


def draw_lines(c1, c2, result_image, line, color):
    cv2.rectangle(result_image, c1, c2, color, thickness=line)
    return cv2


def draw_texts(result_image, line, c1, cv2, color, labels, label):
    display_txt = f"{labels[label]}"
    font = max(line - 1, 1)
    t_size = cv2.getTextSize(display_txt, 0, fontScale=line / 3, thickness=font)[0]
    c2 = c1[0] + t_size[0], c1[1] - t_size[1] - 3
    cv2.rectangle(result_image, c1, c2, color, -1)
    cv2.putText(
        result_image,
        display_txt,
        (c1[0], c1[1] - 2),
        0,
        line / 3,
        [255, 255, 255],
        thickness=font,
        lineType=cv2.LINE_AA,
    )
    return cv2


def exec_detect(target_image_path):
    # load label
    labels = current_app.config["LABELS"]
    # load image
    image = Image.open(target_image_path)
    # convert image data to tensor data
    image_tensor = torchvision.transforms.functional.to_tensor(image)

    # load studied model
    model = torch.load(Path(current_app.root_path, "detector", "model.pt"))
    # chage to model eval mode
    model = model.eval()
    # execute eval
    output = model([image_tensor])[0]

    tags = []
    result_image = np.array(image.copy())
    # add label to each object when model detected
    for box, label, score in zip(output["boxes"], output["labels"], output["scores"]):
        if score > 0.5 and labels[label] not in tags:
            # specify line color
            color = make_color(labels)
            # make line
            line = make_line(result_image)
            # specify location of line and label
            c1 = (int(box[0]), int(box[1]))
            c2 = (int(box[2]), int(box[3]))
            # add line to image
            cv2 = draw_lines(c1, c2, result_image, line, color)
            # add label to image
            cv2 = draw_texts(result_image, line, c1, cv2, color, labels, label)
            tags.append(labels[label])

    # generate image after detection
    detected_image_file_name = str(uuid.uuid4()) + ".jpg"

    # fetch location for image copy
    detected_image_file_path = str(
        Path(current_app.config["UPLOAD_FOLDER"], detected_image_file_name)
    )

    # Copy convert image file to the location
    cv2.imwrite(detected_image_file_path, cv2.cvtColor(result_image, cv2.COLOR_RGB2BGR))

    return tags, detected_image_file_name


def save_detected_image_tags(user_image, tags, detected_image_file_name):
    # store save location of processed image
    user_image.image_path = detected_image_file_name
    # make detetion flag True
    user_image.is_detected = True
    db.session.add(user_image)

    # make user_images_tags record
    for tag in tags:
        user_image_tag = UserImageTag(user_image_id=user_image.id, tag_name=tag)
        db.session.add(user_image_tag)

    db.session.commit()


# make endpoint using dt app
@dt.route("/")
def index():
    # Fetch image list by joing User and UserImage table
    user_images = (
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id)
        .all()
    )

    # fetch tag list
    user_image_tag_dict = {}
    for user_image in user_images:
        # fetch tag list for each images
        user_image_tags = (
            db.session.query(UserImageTag)
            .filter(UserImageTag.user_image_id == user_image.UserImage.id)
            .all()
        )
        user_image_tag_dict[user_image.UserImage.id] = user_image_tags

    # make instance of object detection form
    detector_form = DetectorForm()
    # make instance of object delete form
    delete_form = DeleteForm()

    return render_template(
        "detector/index.html",
        user_images=user_images,
        # pass tag list
        user_image_tag_dict=user_image_tag_dict,
        # pass object detection form
        detector_form=detector_form,
        # pass image delete form
        delete_form=delete_form,
    )


# make endpoint for image upload
@dt.route("/images/<path:filename>")
def image_file(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER"], filename)


# upload path
@dt.route("/upload", methods=["GET", "POST"])
@login_required
def upload_image():
    # validation using UploadImageForm
    form = UploadImageForm()
    if form.validate_on_submit():
        # fetch uploaded image file
        file = form.image.data
        # retrieve file name and extension and convert file name to uuid
        ext = Path(file.filename).suffix
        print(ext)
        image_uuid_file_name = str(uuid.uuid4()) + ext
        print(image_uuid_file_name)
        # save file
        image_path = Path(current_app.config["UPLOAD_FOLDER"], image_uuid_file_name)
        file.save(image_path)

        # save to DB
        user_image = UserImage(user_id=current_user.id, image_path=image_uuid_file_name)
        db.session.add(user_image)
        db.session.commit()

        return redirect(url_for("detector.index"))
    return render_template("detector/upload.html", form=form)


#
@dt.route("/detect/<string:image_id>", methods=["POST"])
# login_required decorator added
@login_required
def detect(image_id):
    # fetch record from user_images table
    user_image = db.session.query(UserImage).filter(UserImage.id == image_id).first()
    if user_image is None:
        flash("物体検知対象の画像が存在しません。")
        return redirect(url_for("detector.index"))

    # fetch image file path for object detection
    target_image_path = Path(current_app.config["UPLOAD_FOLDER"], user_image.image_path)

    # get tags and image file path after object detection
    tags, detected_image_file_name = exec_detect(target_image_path)

    try:
        # store tags and image file path to db
        save_detected_image_tags(user_image, tags, detected_image_file_name)
    except SQLAlchemyError as e:
        flash("物体検知処理でエラーが発生しました。")
        # rollback
        db.session.rollback()
        # output error log
        current_app.logger.error(e)
        return redirect(url_for("detector.index"))

    return redirect(url_for("detector.index"))


@dt.route("/images/delete/<string:image_id>", methods=["POST"])
@login_required
def delete_image(image_id):
    try:
        # delete record from user_image_tags table
        db.session.query(UserImageTag).filter(
            UserImageTag.user_image_id == image_id
        ).delete()

        # delete record from user_images table
        db.session.query(UserImage).filter(UserImage.id == image_id).delete()

        db.session.commit()
    except SQLAlchemyError as e:
        flash("画像削除処理でエラーが発生しました。")
        # output error log
        current_app.logger.error(e)
        db.session.rollback()

    return redirect(url_for("detector.index"))


@dt.route("/images/search", methods=["GET"])
def search():
    # fetch list of images
    user_images = db.session.query(User, UserImage).join(
        UserImage, User.id == UserImage.user_id
    )

    # fetch search word out of GET parameter
    search_text = request.args.get("search")
    user_image_tag_dict = {}
    filtered_user_images = []

    # search tag associated with user_images by looping user_images
    for user_image in user_images:
        # fetch all tags if now keyword is specified
        if not search_text:
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .all()
            )
        else:
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .filter(UserImageTag.tag_name.like("%" + search_text + "%"))
                .all()
            )

            # do not return image if no tag is found
            if not user_image_tags:
                continue
            # fetch tag again if tags remain
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .all()
            )

        # set tags to dictionary which key as user_image_id
        user_image_tag_dict[user_image.UserImage.id] = user_image_tags

        # set image info matrix of filtered result
        filtered_user_images.append(user_image)

    delete_form = DeleteForm()
    detector_form = DetectorForm()

    return render_template(
        "detector/index.html",
        user_images=filtered_user_images,
        user_image_tag_dict=user_image_tag_dict,
        delete_form=delete_form,
        detector_form=detector_form,
    )

apps/detector/templates/detector/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <!-- タイトルを継承先で実装する -->
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!--ナビゲーションバーを作成する。-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('detector.index') }}">detector</a>
            <!-- 画像検索フォームを追加する -->
            {% if url_for(request.endpoint) == url_for('detector.index') or url_for(request.endpoint) ==
            url_for('detector.search') %}
            <div class="btn-group">
                <form action="{{ url_for('detector.search') }}" method="GET" name="dtSearchForm">
                    {% if request.args.get("search") %}
                    <input type="search" id="dt-search" class="form-control col-md-12 dt-search" placeholder="検索"
                        name="search" value="{{ request.args.get('search') }}">
                    {% else %}
                    <input type="search" id="dt-search" class="form-control col-md-12 dt-search" placeholder="検索"
                        name="search">
                    {% endif %}
                </form>
            </div>
            {% endif %}
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">{{ current_user.username }}</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">新規登録</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">ログイン</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- block contentをsection class="container"で囲む -->
    <section class="container">
        {% block content %}{% endblock %}
    </section>

</body>

</html>

apps/detector/templates/detector/index.html
{% extends "detector/base.html" %}
{% block content %}
<!-- flashエラーを表示する -->
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li class="flash">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}

<!-- 画像アップロード画面へのリンクを追加する。-->
<div class="col-md-10 text-right dt-image-register-btn">
    <a href="{{ url_for('detector.upload_image') }}" class="btn btn-primary">画像新規登録</a>
</div>
<!-- 画像一覧を表示する。 -->
{% for user_image in user_images %}
<div class="card col-md-7 dt-image-content">
    <header class="d-flex justify-content-between">
        <div class="dt-image-username">
            {{ user_image.User.username }}
        </div>
        <div class="d-flex flex-row-reverse">
            <!-- 削除ボタンのフォームを追加する　-->
            <div class="p-2">
                <form action="{{ url_for('detector.delete_image', image_id=user_image.UserImage.id) }}" method="POST">
                    {{ delete_form.csrf_token }}
                    {% if current_user.id == user_image.User.id %}
                    {{ delete_form.submit(class="btn btn-danger") }}
                    {% else %}
                    {{ delete_form.submit(class="btn btn-danger", disabled="disabled") }}
                    {% endif %}
                </form>
            </div>
            <!-- 物体検知フォームを追加する　-->
            <div class="p-2">
                <form action="{{ url_for('detector.detect', image_id=user_image.UserImage.id) }}" method="POST">
                    {{ detector_form.csrf_token }}
                    {% if current_user.id == user_image.User.id and user_image.UserImage.is_detected == False %}
                    {{ detector_form.submit(class="btn btn-primary") }}
                    {% else %}
                    {{ detector_form.submit(class="btn btn-primary", disabled="disabled") }}
                    {% endif %}
                </form>
            </div>
        </div>
    </header>
    <section>
        <img src="{{ url_for('detector.image_file', filename=user_image.UserImage.image_path) }}" alt="アップロード画像" />
    </section>
    <!-- タグ情報を表示する -->
    <footer>
        {% for tag in user_image_tag_dict[user_image.UserImage.id] %}
        #{{ tag.tag_name}}
        {% endfor %}
    </footer>
</div>
{% endfor %}
{% endblock %}

apps/detector/templates/detector/upload.html
{% extends "detector/base.html" %}
{% block content %}
<div>
    <h4>新規作成</h4>
    <p>アップロードする画像を選択してください</p>
    <form action="{{ url_for('detector.upload_image') }}" method="post" enctype="multipart/form-data"
        novalidate="novalidate">
        {{ form.csrf_token }}
        <div>
            <label>
                <span> {{ form.image(class="form-control-file") }} </span>
            </label>
        </div>
        {% for error in form.image.errors %}
        <span style="color:red;">{{ error }}</span>
        {% endfor %}
        <hr />
        <div>
            <label>{{ form.submit(class="btn btn-primary") }}</label>
        </div>
    </form>
</div>
{% endblock %}